### DISCUSSION TITLE
Lights vs Switches

### DISCUSSION THREAD

**Discussion by Roving-Ronin** [Cossid/TasmotaDeviceGroupsForESPHome#12] [General]
Hi,

Given I can't see any documentation clarifying the use of 'lights' vs 'switches', would anyone who knows please be able to assist in explaining their usage. I assumed switch is literally the switch we're using for On/Off the lights, but wondering how this is linked/interacts with the lights in the group.

As per:

```
external_components:
  - source: github://cossid/tasmotadevicegroupsforesphome@main
    components: [ device_groups ]
    refresh: 10 min

device_groups:
  - group_name: "testgroup1"         # Tasmota device group name
    send_mask: 0xFFFFFFFF    # Optional, defaults to 0xFFFFFFFF (send everything).  Can be integer or hex
    receive_mask: 0xFFFFFFFF # Optional, defaults to 0xFFFFFFFF (receive everything).  Can be integer or hex
    switches:
      - gpio_switch          # ESPHome entity id
      - template_switch      # ESPHome entity id
    lights:
      - light_rgbww1         # ESPHome entity id
      - light_rgbww2         # ESPHome entity id
```

At the moment I'm using a virtual relay on a Athom Wall Switch (as the physical relay is on 24x7 to provide power to the LED lights downstream that are ESP devices themselves and using Tasmota Groups to remotely ON/OFF them). Config for the Wall Switch (4 gang) is: https://github.com/Roving-Ronin/myHomeAssistant/blob/main/esphome/mydevices/light-switch-front-door.yaml

The downstream ESP lights then have this as their Tasmota Groups config, allowing them to be controlled:
```
device_groups:
  - group_name: "garage-eave-lights"  # Tasmota device group name
    send_mask: 0x0                    # Optional, defaults to 0xFFFFFFFF (send everything).  Can be integer or hex
    receive_mask: 0xFFFFFFFF          # Optional, defaults to 0xFFFFFFFF (receive everything).  Can be integer or hex
    lights:
      - downlight                     # ESPHome entity id
```

The standard config (template) for these lights is: https://github.com/Roving-Ronin/myHomeAssistant/blob/main/esphome/aldi-casalux-smart-led-rgbw.yaml

Just wondering if I'm doing it incorrectly and if I should just be specifying switches on the Wall Switch base config, then defining Tasmota Group 'switches:' upon that device and then 'lights' only on the actual lights and since the physical wall switch and LED lights are part of the same group_name they'll then merge it all to know if the switch member changes, then the light members need to change also?
