### ISSUE TITLE
build errors,

### ISSUE THREAD

**Issue by bkbartk** [Cossid/TasmotaDeviceGroupsForESPHome#1]
I got pointed out to this repo,

but When I try this I get builderrors
```
Compiling /data/keuken-aanrecht/.pioenvs/keuken-aanrecht/src/esphome/components/light/light_json_schema.cpp.o
In file included from src/esphome/components/device_groups/device_groups.cpp:1:
src/esphome/components/device_groups/device_groups.h:271:3: error: 'bools' does not name a type; did you mean 'bool'?
  271 |   bools DeviceGroupsStart();
      |   ^~~~~
      |   bool
src/esphome/components/device_groups/device_groups.cpp: In member function 'virtual void esphome::device_groups::device_groups::loop()':
src/esphome/components/device_groups/device_groups.cpp:140:9: error: 'DeviceGroupsStart' was not declared in this scope; did you mean 'DeviceGroupsStop'?
  140 |     if (DeviceGroupsStart()) {
      |         ^~~~~~~~~~~~~~~~~
      |         DeviceGroupsStop
src/esphome/components/device_groups/device_groups.cpp: At global scope:
src/esphome/components/device_groups/device_groups.cpp:211:6: error: no declaration matches 'bool esphome::device_groups::device_groups::DeviceGroupsStart()'
  211 | bool device_groups::DeviceGroupsStart() {
      |      ^~~~~~~~~~~~~
src/esphome/components/device_groups/device_groups.cpp:211:6: note: no functions named 'bool esphome::device_groups::device_groups::DeviceGroupsStart()'
In file included from src/esphome/components/device_groups/device_groups.cpp:1:
src/esphome/components/device_groups/device_groups.h:243:7: note: 'class esphome::device_groups::device_groups' defined here
  243 | class device_groups : public Component {
      |       ^~~~~~~~~~~~~
src/esphome/components/device_groups/device_groups.cpp: In member function 'bool esphome::device_groups::device_groups::_SendDeviceGroupMessage(int32_t, esphome::device_groups::DevGroupMessageType, ...)':
src/esphome/components/device_groups/device_groups.cpp:856:19: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
  856 |       while (item = *previous_message_ptr++) {
      |              ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
Compiling /data/keuken-aanrecht/.pioenvs/keuken-aanrecht/src/esphome/components/light/light_output.cpp.o
*** [/data/keuken-aanrecht/.pioenvs/keuken-aanrecht/src/esphome/components/device_groups/device_groups.cpp.o] Error 1
========================= [FAILED] Took 16.85 seconds =========================
```

on the esp8266 platform.

**Comment by Cossid** [comment]
Oops, typo in a commit.  Fixed, please try again.

**Comment by bkbartk** [comment]
thanks, building works,
however receiving the signal fails, sending seems to work.

When I have the device is a group toghtter with a tasmota device. Data send from esp-home is received by tasmota, but not the other way around.
when I flash the other device also with esphome the is no working connection in both ways. 
which is why I think receiving fails.

could this be because I have api encryption enabled or a web password set?

**Comment by Cossid** [comment]
No, encryption and passwords shouldn't matter for this, the communication is separate from those features.

Can you post logs of the failures you are receiving, or are there no errors?  Is you network segmented into vlans?
Can you post your light/switch configs?  It may just be that a device configuration isn't handled yet.  I've only tested with switches and rgbww lights so far.

**Comment by bkbartk** [comment]
I actually only tried with swichtes, no errors in the log and no vlan's
but I noticed this
![image](https://github.com/Cossid/TasmotaDeviceGroupsForESPHome/assets/17070805/95de74ec-faba-43de-9981-82f116a14d02)
this is when the client recieved the comment. the esplogs clearly shows the status is set to off, however this won't be applied, only some of the times.
this issue also sometimes makes the toggle show the opposite is the actual status? (so toggle on webapi is on, and the switch is off)
not really sure how to describe.

my switch config is like this
```
switch:
  - platform: gpio
    name: ${switch_name_1}
    pin: GPIO12
    id: switch_1
    on_turn_on:
      then:
      - script.execute: set_status_led
    on_turn_off:
      then:
      - script.execute: set_status_led
  - platform: gpio
    name: ${switch_name_2}
    pin: GPIO5
    id: switch_2
    on_turn_on:
      then:
      - script.execute: set_status_led
    on_turn_off:
      then:
      - script.execute: set_status_led
  - platform: gpio
    name: ${switch_name_3}
    pin: GPIO4
    id: switch_3
    on_turn_on:
      then:
      - script.execute: set_status_led
    on_turn_off:
      then:
      - script.execute: set_status_led
  
light:
  - platform: status_led
    id: stat_led
    pin:
      number: GPIO13
      inverted: yes
script:
  - id: set_status_led
    then:
    - if:
        condition:
           or:
             - switch.is_on: switch_1
             - switch.is_on: switch_2
             - switch.is_on: switch_3
        then:
        - if:
            condition:
              - light.is_on: stat_led
            then:
            - light.turn_off: stat_led
            - delay: 200ms
            - light.turn_on: stat_led
        else:
          - light.turn_off: stat_led
    mode: restart
```

and group config
```
external_components:
  - source: github://cossid/tasmotadevicegroupsforesphome@main
    components: [ device_groups ]
    refresh: 10 min

device_groups:
  - id: "Kitchen1"     # Tasmota device group name
    switches:
      - switch_1
  - id: "Kitchen2"     # Tasmota device group name
    switches:
      - switch_2
  - id: "Kitchen3"     # Tasmota device group name
    switches:
      - switch_3
```

Hope this info is useful as I don't have more loginfo.
if you need more, I can try other log levels.

**Comment by Cossid** [comment]
I can reproduce this with devices with just switches.  Strange that they seem to work when together with lights.  I'll look into this and follow up.

**Comment by Cossid** [comment]
Are the devices you are using ESP-based, or do you have non-esp based ESPHome devices?

**Comment by Cossid** [comment]
After a bunch of testing, I have found my reproduction case wasn't correct.  My wifi router was transferring the send packets, but dropping the receive packets.  I rebooted my wifi router, and everything started working as expected again.  My group of just switches is working exactly as expected.

**Comment by bkbartk** [comment]
no I have esp8285 devices
```
esp8266:
  board: esp8285
  restore_from_flash: true
  early_pin_init: false
```
but I think something inside esphome gets messed up/overwritten.
somehow the state on the site doesn't always represent the real state.

I tried disabling the script, but that didn't work either.
Do I need something like optimistic for the switches?

**Comment by Cossid** [comment]
I've noticed that both HA & ESPHome's `web_server` don't always properly update in real-time (it's hit-and-miss), but just refreshing the pages will show the current state.  You shouldn't need optimistic for anything gpio afaik.

**Comment by Cossid** [comment]
Just to be clear, the state display not refreshing is not a bug in DeviceGroups code, that is purely ESPHome core.  Additionally, I have noticed that the code tries to sync states, but sometimes it can't, and therefore will not sync until both of them match, but again, that code is unchanged from Tasmota.  If the devices are physically responding, then DeviceGroups is working correctly.  There is no display code in DeviceGroups.

ESP8266 should be able to handle this fine, as far as I'm aware, these are very small communication packets.

**Comment by bkbartk** [comment]
> the state display not refreshing is not a bug in DeviceGroups code, that is purely ESPHome core

true,
also I think the state changing but not the relay might be an ESPhome issue, a conflict somewhere
I wanted to set loglevel "VERBOSE" or "VERYVERBOSE" to see what is happening,
But then I get this error.
```
Compiling /data/keuken-aanrecht/.pioenvs/keuken-aanrecht/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
In file included from /data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/Arduino.h:286,
                 from /data/keuken-aanrecht/.piolibdeps/keuken-aanrecht/ArduinoJson/src/ArduinoJson/Configuration.hpp:156,
                 from /data/keuken-aanrecht/.piolibdeps/keuken-aanrecht/ArduinoJson/src/ArduinoJson.hpp:7,
                 from /data/keuken-aanrecht/.piolibdeps/keuken-aanrecht/ArduinoJson/src/ArduinoJson.h:9,
                 from src/esphome/components/json/json_util.h:11,
                 from src/esphome/core/string_ref.h:10,
                 from src/esphome/core/entity_base.h:5,
                 from src/esphome/components/binary_sensor/binary_sensor.h:4,
                 from src/esphome/core/application.h:13,
                 from src/esphome/components/device_groups/device_groups.h:3,
                 from src/esphome/components/device_groups/device_groups.cpp:1:
src/esphome/components/device_groups/device_groups.cpp: In member function 'void esphome::device_groups::device_groups::SendReceiveDeviceGroupMessage(esphome::device_groups::device_group*, esphome::device_groups::device_group_member*, uint8_t*, int, bool)':
src/esphome/components/device_groups/device_groups.cpp:589:17: error: initializer fails to determine size of '__pstr__'
  589 |   ESP_LOGV(TAG, log_buffer);
/data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/WString.h:39:76: note: in definition of macro 'FPSTR'
   39 | #define FPSTR(pstr_pointer) (reinterpret_cast<const __FlashStringHelper *>(pstr_pointer))
      |                                                                            ^~~~~~~~~~~~
src/esphome/core/log.h:67:36: note: in expansion of macro 'F'
   67 | #define ESPHOME_LOG_FORMAT(format) F(format)
      |                                    ^
src/esphome/core/log.h:83:61: note: in expansion of macro 'ESPHOME_LOG_FORMAT'
   83 |   esp_log_printf_(ESPHOME_LOG_LEVEL_VERBOSE, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                             ^~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:151:28: note: in expansion of macro 'esph_log_v'
  151 | #define ESP_LOGV(tag, ...) esph_log_v(tag, __VA_ARGS__)
      |                            ^~~~~~~~~~
src/esphome/components/device_groups/device_groups.cpp:589:3: note: in expansion of macro 'ESP_LOGV'
  589 |   ESP_LOGV(TAG, log_buffer);
      |   ^~~~~~~~
src/esphome/components/device_groups/device_groups.cpp:589:17: error: array must be initialized with a brace-enclosed initializer
  589 |   ESP_LOGV(TAG, log_buffer);
/data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/WString.h:39:76: note: in definition of macro 'FPSTR'
   39 | #define FPSTR(pstr_pointer) (reinterpret_cast<const __FlashStringHelper *>(pstr_pointer))
      |                                                                            ^~~~~~~~~~~~
src/esphome/core/log.h:67:36: note: in expansion of macro 'F'
   67 | #define ESPHOME_LOG_FORMAT(format) F(format)
      |                                    ^
src/esphome/core/log.h:83:61: note: in expansion of macro 'ESPHOME_LOG_FORMAT'
   83 |   esp_log_printf_(ESPHOME_LOG_LEVEL_VERBOSE, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                             ^~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:151:28: note: in expansion of macro 'esph_log_v'
  151 | #define ESP_LOGV(tag, ...) esph_log_v(tag, __VA_ARGS__)
      |                            ^~~~~~~~~~
src/esphome/components/device_groups/device_groups.cpp:589:3: note: in expansion of macro 'ESP_LOGV'
  589 |   ESP_LOGV(TAG, log_buffer);
      |   ^~~~~~~~
src/esphome/components/device_groups/device_groups.cpp: In member function 'bool esphome::device_groups::device_groups::_SendDeviceGroupMessage(int32_t, esphome::device_groups::DevGroupMessageType, ...)':
src/esphome/components/device_groups/device_groups.cpp:860:19: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
  860 |       while (item = *previous_message_ptr++) {
      |              ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
*** [/data/keuken-aanrecht/.pioenvs/keuken-aanrecht/src/esphome/components/device_groups/device_groups.cpp.o] Error 1
========================= [FAILED] Took 50.80 seconds =========================
```
which I think is devicegroups, but not sure.

"ESP8266 should be able to handle this fine, as far as I'm aware, these are very small communication packets."
Still something gets messed up, I tried a lot of different configs, And I will try some more.
if I find something I will let you know

**Comment by Cossid** [comment]
Strange, it compiles for ESP32, but not ESP8266 when increasing log levels, not sure why.  I'll see if I can figure it out, I'll also test specifically on an esp8266 device.  Just a heads-up, moving forward, `id` under `device_groups` has been renamed to `group_name`

**Comment by Cossid** [comment]
It should compile now at increased logging levels on ESP8266 now.  I won't be able to try any physical devices testing until later this evening.

**Comment by bkbartk** [comment]
> moving forward, `id` under `device_groups` has been renamed to `group_name`

I noticed ;)

And I was able to add verbose logging, And I actually found something missing in the log.
(now I'm wondering, probably this info is also visible at "DEBUG" level, but I didn'l ook close enougth
When I receive a message from the device group the log is like this
```
21:33:15	[V]	[dgr:589]	Sending KitchenFornuis message to 192.168.180.187: seq=12, flags=8
21:33:15	[D]	[switch:055]	'Keuken Fornuis': Sending state ON
21:33:16	[V]	[json:036]	Attempting to allocate 512 bytes for JSON serialization
21:33:16	[V]	[json:056]	Size after shrink 72 bytes
21:33:16	[V]	[dgr:589]	Received KitchenFornuis message from 192.168.180.187: seq=12, flags=0, 128=335544321*
21:33:48	[V]	[dgr:589]	Sending KitchenFornuis message to network: seq=2, flags=64
```
and when I use the switch this is the log
```
21:34:26	[V]	[dgr:589]	Received KitchenFornuis message from 192.168.180.187: seq=3, flags=8
21:34:32	[D]	[switch:012]	'Keuken Fornuis' Turning ON.
21:34:32	[D]	[switch:055]	'Keuken Fornuis': Sending state ON
21:34:32	[V]	[dgr:589]	Sending KitchenFornuis message to network: seq=4, flags=0, 128=335544321
21:34:32	[V]	[dgr:589]	Received KitchenFornuis message from local: seq=4, flags=0, 128=335544321*
21:34:32	[V]	[json:036]	Attempting to allocate 512 bytes for JSON serialization
21:34:33	[V]	[json:056]	Size after shrink 72 bytes
21:34:33	[V]	[dgr:589]	Received KitchenFornuis message from 192.168.180.187: seq=4, flags=8
```

the actual line 
`[D]	[switch:012]	'Keuken Fornuis' Turning ON.`
is never there when the messages is received from device group.

**Comment by Cossid** [comment]
That is actually normal.  The device you triggered from is using `turn_on` or `turn_off` which prints that message, but receiving from a group is actually using a more generic `publish_state` which doesn't print that message.

**Comment by Cossid** [comment]
I see you have multiple groups, do you also have multiple corresponding groups on a corresponding Tasmota device, or is it a single group on different devices?  It's possible this could have something to do with Tasmota's flags on devices with multiple groups (so88 1)

**Comment by bkbartk** [comment]
clear,
I noticed something else
I have 3 groups
```
device_groups:
  - group_name: "KitchenFornuis"     # Tasmota device group name
    switches:
      - switch_1
  - group_name: "KitchenAanrecht"     # Tasmota device group name
    switches:
      - switch_2
  - group_name: "KitchenTafel"     # Tasmota device group name
    switches:
      - switch_3
```
yet in verbose logging, I only see my first group.
switches sometimes seem to be set, but the wrong one.

```
23:22:08	[V]	[json:056]	Size after shrink 72 bytes
23:22:12	[D]	[switch:012]	'Keuken Aanrecht' Turning ON.
23:22:12	[D]	[switch:055]	'Keuken Aanrecht': Sending state ON
23:22:13	[V]	[dgr:589]	Sending KitchenFornuis message to network: seq=4, flags=0, 128=335544321
23:22:14	[V]	[dgr:589]	Received KitchenFornuis message from local: seq=4, flags=0, 128=335544321*
23:22:14	[V]	[json:036]	Attempting to allocate 512 bytes for JSON serialization
23:22:14	[V]	[json:056]	Size after shrink 72 bytes
23:22:16	[V]	[dgr:589]	Sending KitchenFornuis message to network: seq=4, flags=0, 128=335544321
23:22:16	[V]	[dgr:589]	Received KitchenFornuis message from 192.168.180.152: seq=4, flags=8
23:22:18	[V]	[dgr:589]	Received KitchenFornuis message from 192.168.180.152: seq=4, flags=8
23:22:18	[D]	[switch:012]	'Keuken Fornuis Aanrecht' Turning ON.
23:22:19	[D]	[switch:055]	'Keuken Fornuis Aanrecht': Sending state ON
23:22:19	[V]	[dgr:589]	Sending KitchenFornuis message to network: seq=5, flags=0, 128=335544321
23:22:19	[V]	[dgr:589]	Received KitchenFornuis message from local: seq=5, flags=0, 128=335544321*
23:22:19	[V]	[json:036]	Attempting to allocate 512 bytes for JSON serialization
23:22:19	[V]	[json:056]	Size after shrink 80 bytes
23:22:19	[V]	[dgr:589]	Sending KitchenFornuis message to network: seq=5, flags=0, 128=335544321
23:22:19	[V]	[dgr:589]	Received KitchenFornuis message from 192.168.180.152: seq=5, flags=8
23:22:20	[V]	[dgr:589]	Received KitchenFornuis message from 192.168.180.152: seq=5, flags=8
23:22:22	[D]	[switch:012]	'Keuken Tafel Aanrecht' Turning ON.
23:22:22	[D]	[switch:055]	'Keuken Tafel Aanrecht': Sending state ON
23:22:22	[V]	[dgr:589]	Sending KitchenFornuis message to network: seq=6, flags=0, 128=335544321
23:22:22	[V]	[dgr:589]	Received KitchenFornuis message from local: seq=6, flags=0, 128=335544321*
23:22:22	[V]	[json:036]	Attempting to allocate 512 bytes for JSON serialization
23:22:23	[V]	[json:056]	Size after shrink 80 bytes
23:22:23	[V]	[dgr:589]	Sending KitchenFornuis message to network: seq=6, flags=0, 128=335544321
23:22:23	[V]	[dgr:589]	Received KitchenFornuis message from 192.168.180.152: seq=6, flags=8
23:22:23	[V]	[dgr:589]	Received KitchenFornuis message from 192.168.180.152: seq=6, flags=8
```

**Comment by Cossid** [comment]
Are you certain you don't just have the wrong name on your switch entities?

Each "group" loads a separate instance of the code, and is managed separately, there is no way to mix them together.  Everything [dgr..] is showing the group name, everything [switch..] is from your entities directly.

It is also possible that is something I broken when changing to `group_name`, I'll look into that.

**Comment by bkbartk** [comment]
> I see you have multiple groups, do you also have multiple corresponding groups on a corresponding Tasmota device, or is it a single group on different devices? It's possible this could have something to do with Tasmota's flags on devices with multiple groups (so88 1)

right now I do not have a correspronding tasmota devices,
those are now 2 equal esphome devices having the same configuration except from some names.
before I had 1 group with 3 switches, but was afraid that was the issue, so I decided to split them up.

**Comment by Cossid** [comment]
Yeah, multiple device groups were very much broken.  Please update and try again.

Interesting on the turn_on/off + publish state.  I'll apply that shortly.

**Comment by Cossid** [comment]
Added the turn_on/off along with the publish_state.  Please let me know how things go.

**Comment by Cossid** [comment]
Ah I broke everything, won't compile, just a sec.

**Comment by Cossid** [comment]
With the code in its current state, everything is working for me on a pair of esp8266 plugs.

**Comment by bkbartk** [comment]
really wierd,
for me I only get on both of my devices
```
[09:00:16][E][dgr:213]: Error subscribing
[09:00:16][E][dgr:213]: Error subscribing
[09:00:16][E][dgr:213]: Error subscribing
[09:00:16][E][dgr:213]: Error subscribing
[09:00:16][E][dgr:213]: Error subscribing
[09:00:16][E][dgr:213]: Error subscribing
```
and the  devices go in some kind of bootloop
loglevel back to "DEBUG" so I don't have more info.

**Comment by bkbartk** [comment]
and if I use only one group like this, 
(currently no other devices are in this group, but I also tested with one tasmota device in this group and the result was the same)
```
device_groups:
  - group_name: "KitchenHome"     # Tasmota device group name
    switches:
      - switch_1
      - switch_2
      - switch_3
```
there is no errors, and no bootloop, which is good.
however all switches toggle together.
so I click switch 1 and then switch 2 and 3 get in sync
