### ISSUE TITLE
LibreTiny support

### ISSUE THREAD

**Issue by bkbartk** [Cossid/TasmotaDeviceGroupsForESPHome#3]
Hello,

apparently I'm the only one creating issues here.
But I was wondering if there will be LibreTiny support for this module.
I know you are aware of Libretiny as I saw your name popping up at some cloud cutter changes, so I skip the part where I explain what it does.
Right now when I apply device grouping on and RGBWW bulb with libretiny 1.2 or 1.4 device grouping looks ok.
but after changing the color temperature a couple of times the bulb goes dark/off until a restart. the interface does not know this and thinks everything is still ok. (this can also be an RGB issue I realize now)

my goal is to be able to use the wall mounted buttons to turn on/off the  bulb. 
As a workaround I now use automations but somehow for me the delay is always just to long.

**Comment by Cossid** [comment]
I believe this is indeed more of an RGB/RGBWW issue than a LibreTiny issue.  I know everything compiles fine, but I have also noticed a similar issue with bulbs running LibreTiny where the RGB portions work correctly, but the white channels fail to update, and rebooting seems to be the only solution.  I'll look into this as time permits.

**Comment by bkbartk** [comment]
I think it's PWM, but I'm not sure.
my config is like this
```
esphome:
  name: ${device_name}
  friendly_name: ${device_name}

bk72xx:
  # framework:
  #   version: dev  #for dev now
  board: generic-bk7231t-qfn32-tuya

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

output:
  - platform: libretiny_pwm #ledc
    id: output_red
    pin: P26
  - platform: libretiny_pwm #ledc
    id: output_green
    pin: P6
  - platform: libretiny_pwm #ledc
    id: output_blue
    pin: P24
  - platform: libretiny_pwm #ledc
    id: output_cold
    pin: P8
  - platform: libretiny_pwm #ledc
    id: output_warm
    pin: P7

light:
  - platform: rgbww
    restore_mode: RESTORE_DEFAULT_ON
    id: light_rgbww
    name: ${switch_name}
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm
```
(on libretiny 1.2 I used ledc)

the strange thing is that for me the issue occurs when the bulb is the sending device, not the receiving one.
- on one side I have the bulb, and on the other side just a simple swich.
```
# external_components:
#     - source: github://cossid/tasmotadevicegroupsforesphome@main
#       components: [ device_groups ]
#       refresh: 10 min

# device_groups:
#   - group_name: "bulbkamervoor"     # Tasmota device group name
#     lights:
#       - light_rgbww
```
```
# external_components:
#     - source: github://cossid/tasmotadevicegroupsforesphome@main
#       components: [ device_groups ]
#       refresh: 10 min

# device_groups:
#   - group_name: "bulbkamerachter"     # Tasmota device group name
#     switches:
#       - dummy_bulb_achter
#   - group_name: "bulbkamervoor"     # Tasmota device group name
#     switches:
#       - dummy_bulb_voor
```
but the issue occurs when chaning the light temperature a couple of times in home assistant.

and when disabling the component the issue is gone.
