### ISSUE TITLE
First control from different device than what's used until that point fails to propagate

### ISSUE THREAD

**Issue by TMaYaD** [Cossid/TasmotaDeviceGroupsForESPHome#8]
I use device groups to sync my wall touch switches with light channels. The device groups work wonderfully most of the time. The only problem is when I try to switch OFF using a different device to the one I used to switch ON.

Ex: 
- Turn ON using wall switch, Light turns ON
  Turn OFF using wall switch, Lights turns OFF ✅ 
- Turn ON using Light, Switch turns ON
  Turn OFF using Light, Switch turns OFF ✅ 

- Turn ON using wall switch, Light goes ON
  Turn OFF using Light, Switch stays ON ❌
  Turn OFF light, Turn it back ON and then turn it OFF one more time, Switch turns OFF
- Turn ON using Light, Switch turns ON
  Turn OFF using switch, Light stays ON ❌
  Turn OFF switch, Turn it back ON and then turn it OFF one more time, Light turns OFF

**Comment by TMaYaD** [comment]
Changed the title because as I was experimenting, I saw the same happen when trying to turn light "ON" as well.

**Comment by TMaYaD** [comment]
Here's a sample log from the light:

```
05:55:42	[D]	[light:036]	
'theater Room Lights' Setting:
05:55:42	[D]	[light:047]	
  State: ON
05:55:42	[D]	[light:085]	
  Transition length: 1.0s
05:55:42	[D]	[dgr:736]	
Sending theater-lights message to network: seq=79, flags=0, 128=335544321
05:55:42	[D]	[dgr:736]	
Sending theater-lights message to network: seq=80, flags=0, 128=335544321, 224=209,0,255,255,255,0
05:55:42	[D]	[dgr:736]	
Received theater-lights message from 10.10.10.211: seq=79, flags=8
05:55:42	[D]	[dgr:736]	
Received theater-lights message from 10.10.10.211: seq=80, flags=8
05:55:47	[D]	[dgr:736]	
Sending theater-lights message to 10.10.10.211: seq=43, flags=8
05:55:47	[D]	[dgr:736]	
Received theater-lights message from 10.10.10.211: seq=43, flags=0, 128=335544320*
```

I was using the light's web interface @ 05:55:42 and the touch switch at @ 05:55:47. The message is received fine. But for some reason the light chooses to ignore it.

**Comment by Cossid** [comment]
While I'm sure this happens, and have likely experienced myself in production when I'm not able to debug, I can't currently reproduce it intentionally.  I can Turn on with a switch, off with a light, and back on with the original switch on the first try.  I can also do the inversion of that (light->switch->light).

Do you have any custom masks set?

**Comment by TMaYaD** [comment]
Yes.

```yaml
  - group_name: "theater-lights"
    receive_mask: 0x00000041 # Optional, defaults to 0xFFFFFFFF (receive everything).  Can be integer or hex
    lights:
      - light_1
```

I use this so that brightness is not reset to full when turned on using the switch.

**Comment by TMaYaD** [comment]
FWIW, I can reproduce it intentionally and would be happy to assist with any debugging.

**Comment by Cossid** [comment]
There isn't much good in you debugging if it's not fully reproducible for me, I won't be able to test what may need to be fixed.

Providing more information would be a better start.
What platform is the switch running on, what platform is the bulb running on?
What are the configs for each device?

**Comment by TMaYaD** [comment]
Lights are H801. Switches are Tuya touch switches.

Full Light Config:
```yaml
substitutions:
  area: theater
  device: lights
  ip: 10.10.10.214
esphome:
  name: theater-lights
  area: theater
  build_path: build/theater-lights
  friendly_name: ''
  platformio_options: {}
  includes: []
  libraries: []
  name_add_mac_suffix: false
  min_version: 2023.12.3
esp8266:
  board: esp01_1m
  restore_from_flash: true
  framework:
    version: 3.0.2
    source: ~3.30002.0
    platform_version: platformio/espressif8266@3.2.0
  early_pin_init: true
  board_flash_mode: dout
logger:
  baud_rate: 0
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  logs: {}
  esp8266_store_log_strings_in_flash: true
api:
  encryption:
    key: \033[5m!secret 'encryption_key'\033[6m
  port: 6053
  password: \033[5m''\033[6m
  reboot_timeout: 15min
ota:
  password: \033[5m!secret 'ota_password'\033[6m
  safe_mode: true
  port: 8266
  reboot_timeout: 5min
  num_attempts: 10
wifi:
  manual_ip:
    static_ip: 10.10.10.214
    gateway: 10.10.10.1
    subnet: 255.255.254.0
    dns1: 10.10.8.35
    dns2: 10.10.8.53
  ap:
    ssid: \033[5mtheater-lights\033[6m
    password: \033[5m!secret 'ap_password'\033[6m
    ap_timeout: 1min
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  passive_scan: false
  enable_on_boot: true
  networks:
  - ssid: \033[5m!secret 'wifi_ssid'\033[6m
    password: \033[5m!secret 'wifi_password'\033[6m
    priority: 0.0
  use_address: 10.10.10.214
captive_portal: {}
mqtt:
  broker: 10.10.8.33
  discovery: false
  topic_prefix: theater
  log_topic:
    topic: theater/lights/log
    level: INFO
    qos: 0
    retain: true
  port: 1883
  username: ''
  password: \033[5m''\033[6m
  discovery_retain: true
  discovery_prefix: homeassistant
  discovery_unique_id_generator: legacy
  discovery_object_id_generator: none
  use_abbreviations: true
  keepalive: 15s
  reboot_timeout: 15min
  birth_message:
    topic: theater/status
    payload: online
    qos: 0
    retain: true
  will_message:
    topic: theater/status
    payload: offline
    qos: 0
    retain: true
  shutdown_message:
    topic: theater/status
    payload: offline
    qos: 0
    retain: true
external_components:
- source:
    url: https://github.com/dentra/esphome-components.git
    type: git
  refresh: 1d
  components: all
- source:
    url: https://github.com/cossid/tasmotadevicegroupsforesphome.git
    ref: main
    type: git
  components:
  - device_groups
  refresh: 1d
backup:
  force_update: false
button:
- platform: restart
  name: theater lights Restart
  disabled_by_default: true
  entity_category: config
  device_class: restart
output:
- platform: esp8266_pwm
  id: pwm_r
  pin:
    number: 15
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  frequency: 1000.0
  zero_means_zero: false
- platform: esp8266_pwm
  id: pwm_g
  pin:
    number: 13
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  frequency: 1000.0
  zero_means_zero: false
- platform: esp8266_pwm
  id: pwm_b
  pin:
    number: 12
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  frequency: 1000.0
  zero_means_zero: false
- platform: esp8266_pwm
  id: pwm_w1
  pin:
    number: 14
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  frequency: 1000.0
  zero_means_zero: false
- platform: esp8266_pwm
  id: pwm_w2
  pin:
    number: 4
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  frequency: 1000.0
  zero_means_zero: false
light:
- platform: monochromatic
  id: light_1
  output: pwm_r
  restore_mode: RESTORE_DEFAULT_OFF
  name: theater Room Lights
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
- platform: monochromatic
  id: light_2
  output: pwm_g
  restore_mode: RESTORE_DEFAULT_OFF
  name: theater Entry Lights
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
- platform: monochromatic
  id: light_3
  output: pwm_b
  restore_mode: RESTORE_DEFAULT_OFF
  name: theater Bath Lights
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
- platform: monochromatic
  id: light_4
  output: pwm_w1
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
  name: light_4
  internal: true
- platform: monochromatic
  id: light_5
  output: pwm_w2
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
  name: light_5
  internal: true
device_groups:
- group_name: theater-lights
  lights:
  - light_1
  send_mask: 0xFFFFFFFF
  receive_mask: 0xFFFFFFFF
- group_name: theater-entry-lights
  receive_mask: 0x01
  lights:
  - light_2
  send_mask: 0xFFFFFFFF
- group_name: theater-bath-lights
  receive_mask: 0x01
  lights:
  - light_3
  send_mask: 0xFFFFFFFF
```

Full Switch config:
```yaml
substitutions:
  area: theater
  device: entry
  ip: 10.10.10.211
esphome:
  name: theater-entry
  area: theater
  build_path: build/theater-entry
  friendly_name: ''
  platformio_options: {}
  includes: []
  libraries: []
  name_add_mac_suffix: false
  min_version: 2023.12.3
esp8266:
  board: esp01_1m
  restore_from_flash: true
  framework:
    version: 3.0.2
    source: ~3.30002.0
    platform_version: platformio/espressif8266@3.2.0
  early_pin_init: true
  board_flash_mode: dout
logger:
  baud_rate: 0
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  logs: {}
  esp8266_store_log_strings_in_flash: true
api:
  encryption:
    key: \033[5m!secret 'encryption_key'\033[6m
  port: 6053
  password: \033[5m''\033[6m
  reboot_timeout: 15min
ota:
  password: \033[5m!secret 'ota_password'\033[6m
  safe_mode: true
  port: 8266
  reboot_timeout: 5min
  num_attempts: 10
wifi:
  manual_ip:
    static_ip: 10.10.10.211
    gateway: 10.10.10.1
    subnet: 255.255.254.0
    dns1: 10.10.8.35
    dns2: 10.10.8.53
  ap:
    ssid: \033[5mtheater-entry\033[6m
    password: \033[5m!secret 'ap_password'\033[6m
    ap_timeout: 1min
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  passive_scan: false
  enable_on_boot: true
  networks:
  - ssid: \033[5m!secret 'wifi_ssid'\033[6m
    password: \033[5m!secret 'wifi_password'\033[6m
    priority: 0.0
  use_address: 10.10.10.211
captive_portal: {}
mqtt:
  broker: 10.10.8.33
  discovery: false
  topic_prefix: theater
  log_topic:
    topic: theater/entry/log
    level: INFO
    qos: 0
    retain: true
  port: 1883
  username: ''
  password: \033[5m''\033[6m
  discovery_retain: true
  discovery_prefix: homeassistant
  discovery_unique_id_generator: legacy
  discovery_object_id_generator: none
  use_abbreviations: true
  keepalive: 15s
  reboot_timeout: 15min
  birth_message:
    topic: theater/status
    payload: online
    qos: 0
    retain: true
  will_message:
    topic: theater/status
    payload: offline
    qos: 0
    retain: true
  shutdown_message:
    topic: theater/status
    payload: offline
    qos: 0
    retain: true
external_components:
- source:
    url: https://github.com/dentra/esphome-components.git
    type: git
  refresh: 1d
  components: all
- source:
    url: https://github.com/cossid/tasmotadevicegroupsforesphome.git
    ref: main
    type: git
  components:
  - device_groups
  refresh: 1d
backup:
  force_update: false
button:
- platform: restart
  name: theater entry Restart
  disabled_by_default: true
  entity_category: config
  device_class: restart
tuya: {}
uart:
- rx_pin:
    number: 3
    mode:
      input: true
      output: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  tx_pin:
    number: 1
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  baud_rate: 9600
  rx_buffer_size: 256
  stop_bits: 1
  data_bits: 8
  parity: NONE
switch:
- platform: tuya
  id: switch_1
  switch_datapoint: 1
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  name: switch_1
  internal: true
- platform: tuya
  id: switch_2
  switch_datapoint: 2
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  name: switch_2
  internal: true
- platform: tuya
  id: switch_3
  switch_datapoint: 3
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  name: switch_3
  internal: true
- platform: tuya
  id: switch_4
  switch_datapoint: 4
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  name: switch_4
  internal: true
device_groups:
- group_name: theater-lights
  switches:
  - switch_1
  send_mask: 0xFFFFFFFF
  receive_mask: 0xFFFFFFFF
- group_name: theater-entry-lights
  switches:
  - switch_2
  send_mask: 0xFFFFFFFF
  receive_mask: 0xFFFFFFFF
- group_name: theater-bath-lights
  switches:
  - switch_3
  send_mask: 0xFFFFFFFF
  receive_mask: 0xFFFFFFFF
```

**Comment by Cossid** [comment]
There is a better than 0 chance this is because your switch is TuyaMCU based.  I don't have one to test with, so I'm not sure how to approach that.  Do you have any GPIO-based switches to test if you have the same issues?

Logs from the switch side would probably be more useful here than from the light.

**Comment by TMaYaD** [comment]
I do have sonoff basic I can probably work with. 

However, I'm not convinced it's the switch side that's the problem. In the light logs I shared earlier, you can clearly see the light side receiving the message with payload `335544320`(I'm assuming the last bit is the power) as well as sending an ack. However, it fails to act on the message and turn the light off. 

I'll rerun the test and upload the switch side logs in a bit.

**Comment by bkbartk** [comment]
Sorry, To break in to this thread,

but I have experienced this issue on a few of my configs, but only with a really specific scenario
tuya(libretiny) RGBWW light bulb.
sonoff NSPanel running this blueprint(https://github.com/Blackymas/NSPanel_HA_Blueprint)
when I click the buttons. all look fine,but when I go to HA and adjust the lights, sometimes the nspanel won't follow.
but also in the situation where I have 2 NSpanels and 2 bulbs, the NSpanels won't always follow each other, the scenario happens less often but this happens.
(in none of my other setups i use tuya bulbs or NSPanels and they all work like a charm)

First I thought it was because of tuya, but now I think the NSpanels are just sometimes to busy to receive and process the UDP request.

as a workaround I created a blueprint. to keep my lights and switches in sync. device grouping over UDP works way faster and better, but just in case it might fail, there is a fallback.
My blueprint is like this
```
blueprint:
  name: Combine switches so they turn on/off together
  description: Combine switches so they turn on/off together
  domain: automation
  input:
    switch_1:
      name: switch_1
      description: switch_1
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true
trigger:
  - platform: state
    entity_id: !input switch_1
    to:
      - "on"
      - "off"
action:
  - variables:
      modified_state: "{{ trigger.to_state.state }}"
      switches: !input switch_1
  - repeat:
      for_each: "{{ switches }}"
      sequence:
        - if: "{{ repeat.item.state != modified_state }}"
          then:
            - if: '{{ modified_state == "on" }}'
              then:
                - service: switch.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
              else:
                - service: switch.turn_off
                  target:
                    entity_id: "{{ repeat.item }}"
```
I know it's just workaround, but for me using both, (this component and the bleuprint works best)
